# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9db896bbd517a1a5c9c4f65222d775e8f9533e6fa1e8bff707c5165977da537941a131f9186fc30020e8850247be4f91b73c4f87f8f2affe64d88e5a9a404f1

test:
  secret_key_base: d9e1054c737696d0180ecc87d5c062bb61acd7659430ee0a29dc32ef187575626281089c893f941b2c8f294cb0ab65e2d4ad044465603d5dffe671a9e8ea63f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
